### ISSUE TITLE
Need a widget to hold multiple text boxes of stats for multiple columns

### ISSUE THREAD

**Issue by chendrix99** [EECE3093C/team-project-keith-python-app#48]
If the user selects multiple columns for visualizing, then we need to contain multiple text boxes that display the results of the statistical analysis. The user must be able to scroll and view all selected text boxes corresponding to the different columns selected.

**Comment by chendrix99** [comment]
Please see description of issue #47 for design plan. This issue will fall under implementation for that issue.

**Comment by jakehusemanUC** [comment]
Nice
I think also if possible this widget should use the column titles retrieved from Python, rather than indices or something, since getting them out of CAM will be a pain. If not possible, we can queue a task to add a cam::GetColumnTitles or something similar.

**Comment by chendrix99** [comment]
It should be very possible to just get use the column titles that I am getting on the python side. Currently I am using helper functions that use pythons csv library to parse files.
