### ISSUE TITLE
Create large viewing area for graphs to be displayed in output window

### ISSUE THREAD

**Issue by chendrix99** [EECE3093C/team-project-keith-python-app#49]
We will need some kind of text box or viewing area to place graphs that come with the column analyses. These will most likely be accepting graphs created in the matplotlib section of the repo.

**Comment by jakehusemanUC** [comment]
will there be one graph per analysis?
Probably will need some way of changing which graph is visible, since I think one graph per column returned (mapped against the time column) makes sense

**Comment by chendrix99** [comment]
Yeah I agree, I am thinking that for each column selected there will be a graph of that data plotted against the time column. For all the column selections the user will be able to maybe scroll through the graphs similar to the text areas. Maybe we could also have a single final graph with incorporates all the selected columns in one plot over time.
