### ISSUE TITLE
Implement PyQtGraph functionality to spawn graphs for user selected columns

### ISSUE THREAD

**Issue by chendrix99** [EECE3093C/team-project-keith-python-app#79]
In the graph viewing space that was created in issue #66, we will take the data points of the columns and plot them over the data points of the time column. For each column selection we will create a graph and place it in the viewing area as well as maintain an aggregate graph of all column data if there are more than two columns selected. When user deselects a column, the graph will also be removed.

**Comment by jakehusemanUC** [comment]
this is sounding pretty cool

one thing I'm wondering is what will happen if the user selects a String column? Does the PyQtGraph know how to handle something like that?

in terms of analysis, we are basically only providing the mode (or most common string in the column), so potentially there isn't a need for graphs to be shown for string columns vs time column

**Comment by chendrix99** [comment]
I will need to make a separate issue to handle this case. But yes, string columns may need to be handled differently.
